# Generated by Django 4.2.18 on 2025-01-24 02:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("roulette_app", "0002_roulette_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MaxValueValidator(10000)],
                    ),
                ),
                (
                    "winning_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "number",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(36),
                            django.core.validators.MinValueValidator(0),
                        ]
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[("Red", "Red"), ("Black", "Black")], max_length=5
                    ),
                ),
                (
                    "roulette",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bets",
                        to="roulette_app.roulette",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bets",
                        to="users.user",
                    ),
                ),
            ],
        ),
    ]
