# Generated by Django 4.2.18 on 2025-01-25 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bets", "0002_alter_bet_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bet",
            name="amount",
            field=models.FloatField(
                validators=[
                    django.core.validators.MaxValueValidator(10000),
                    django.core.validators.MinValueValidator(1),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="bet",
            name="winning_amount",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
