# Generated by Django 4.2.18 on 2025-01-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Roulette",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
