# Generated by Django 4.2.18 on 2025-01-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roulette_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roulette",
            name="state",
            field=models.CharField(
                choices=[("Open", "Open"), ("Close", "Close")],
                default="Open",
                max_length=5,
            ),
        ),
    ]
