# Generated by Django 4.2.18 on 2025-01-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roulette_app", "0002_roulette_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roulette",
            name="state",
            field=models.CharField(
                choices=[("Open", "Open"), ("Close", "Close")],
                default="Closed",
                max_length=5,
            ),
        ),
    ]
